#pragma once

#include "driver/spi_master.h"

#define GATEWAY_DEVICE_NAME "PLC01"

#define W5500_SPI_HOST SPI2_HOST
#define W5500_SPI_CLOCK_HZ 20000000
#define W5500_PHY_ADDR 1

#define NETWORK_STATIC_IP_A 0
#define NETWORK_STATIC_IP_B 0
#define NETWORK_STATIC_IP_C 0
#define NETWORK_STATIC_IP_D 0

#define NETWORK_STATIC_GW_A 0
#define NETWORK_STATIC_GW_B 0
#define NETWORK_STATIC_GW_C 0
#define NETWORK_STATIC_GW_D 0

#define NETWORK_STATIC_NETMASK_A 0
#define NETWORK_STATIC_NETMASK_B 0
#define NETWORK_STATIC_NETMASK_C 0
#define NETWORK_STATIC_NETMASK_D 0

#define NETWORK_STATIC_DNS_A 0
#define NETWORK_STATIC_DNS_B 0
#define NETWORK_STATIC_DNS_C 0
#define NETWORK_STATIC_DNS_D 0

#define NETWORK_STATIC_BACKUP_DNS_A 0
#define NETWORK_STATIC_BACKUP_DNS_B 0
#define NETWORK_STATIC_BACKUP_DNS_C 0
#define NETWORK_STATIC_BACKUP_DNS_D 0

#define CLOUD_GOOGLE_SCRIPT_HOST "script.google.com"
#define CLOUD_GOOGLE_SCRIPT_PATH "/macros/s/AKfycby1Htg3a0idXy6TQNXRXqb0zqzmIL4bxeptHTPGlPYOqZ5d1V_3A0G0lpp-6vMSe-jg/exec"
#define CLOUD_GOOGLE_SCRIPT_URL "https://script.google.com/macros/s/AKfycby1Htg3a0idXy6TQNXRXqb0zqzmIL4bxeptHTPGlPYOqZ5d1V_3A0G0lpp-6vMSe-jg/exec"
#define CLOUD_GOOGLE_SCRIPT_PORT 443U
#define CLOUD_GOOGLE_SCRIPT_USE_TLS 1U
